language: go
sudo: false
go:
- '1.10'

before_install:
- go get github.com/mattn/goveralls
- go get github.com/golang/dep/cmd/dep

install:
- dep ensure

script:
- go test -coverprofile=coverage.out ./...
- goveralls -coverprofile=coverage.out -service=travis-ci
